version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rmq
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - gestion_clientes_network

  app:
    build: .
    depends_on:
      - rabbitmq
    environment:
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      MongoDB__ConnectionString: mongodb+srv://jeanvalverde:Valverde24@jeancluster.qdtfszz.mongodb.net/?retryWrites=true&w=majority
      MongoDB__DatabaseName: BDII
      MongoDB__CollectionName: uptBDII
    ports:
      - "5001:80"
    networks:
      - gestion_clientes_network

networks:
  gestion_clientes_network:
    driver: bridge
